### ISSUE TITLE
Need a shortcut

### ISSUE THREAD

**Issue by KevinYaoooooo** [dexterouslogic/super-simple-highlighter#5]
Definitely need a shortcut, pleeeeeeease!

**Comment by technicalflaw** [comment]
A keyboard shortcuts? They're on the options page.

**Comment by KevinYaoooooo** [comment]
I don't see any keyboard shortcuts settings in options page.

![image](https://cloud.githubusercontent.com/assets/12027816/18909242/728234aa-85a5-11e6-8889-8ce174c77f38.png)

**Comment by technicalflaw** [comment]
Oh yes, I forgot, Chrome doesn't promote it very well. It's at the bottom of the Extensions page.

![screen shot 2016-09-28 at 12 25 44](https://cloud.githubusercontent.com/assets/7760019/18911752/ca556f8c-8576-11e6-873d-8cc50cf60b98.png)

**Comment by elliott-beach** [comment]
It's in a different place now. As of Chrome 67, navigate to **chrome://extensions/shortcuts**.
